/**
 * Single source of truth for every user-facing disclaimer mandated by
 * `.claude/rules/HEALTH_RULES.md §Mandatory Disclosures`.
 *
 * Every surface that renders health-adjacent copy MUST import from here.
 * Inline health copy anywhere else in the tree is a rule violation that
 * `pr-reviewer` will flag.
 *
 * When adding a new surface, also add it to `DISCLAIMER_SURFACES` so the
 * test in `tests/unit/disclaimers.test.ts` fails if the surface type has
 * no copy wired up.
 */

export type DisclaimerSurface =
  | "onboardingIntro"
  | "routineStart"
  | "painPromptLow"
  | "painPromptMedium"
  | "painPromptHigh"
  | "safetyGate"
  | "aiGeneratedCard"
  | "marketingPainRelief"

export interface Disclaimer {
  /** Stable id for audit logging + testing. */
  id: DisclaimerSurface
  /** The copy rendered to the user. */
  body: string
  /**
   * Optional CTA link. When present the renderer should show it as a
   * button/link beneath the body.
   */
  cta?: {
    label: string
    /** Always a route on our domain — never an external URL. */
    href: string
  }
  /** Severity drives the visual treatment (neutral / caution / warn). */
  severity: "neutral" | "caution" | "warn"
}

const INTRO_BODY =
  "Bendro provides general flexibility and mobility content. It is not " +
  "medical advice. Consult a qualified healthcare provider before starting " +
  "any new exercise program."

const ROUTINE_START_BODY = "Listen to your body. Stop if you feel sharp pain."

const PAIN_LOW_BODY =
  "Thanks for checking in. Mild soreness is part of stretching — it should " +
  "ease within a day."

const PAIN_MEDIUM_BODY =
  "We'll ease back on similar stretches next time. If this persists, " +
  "consider trying a gentler routine."

const PAIN_HIGH_BODY =
  "If you are experiencing significant pain, please consult a healthcare " +
  "provider. We'll pause similar stretches in your recommendations."

const SAFETY_GATE_BODY =
  "Please speak with a healthcare provider before continuing. We'll " +
  "default your library to gentle routines. You can adjust this later in " +
  "settings."

const AI_GENERATED_BODY =
  "Generated by AI based on your goals. Not a substitute for professional " +
  "guidance."

const MARKETING_PAIN_RELIEF_BODY =
  "Results vary. Bendro does not treat or cure any medical condition."

export const DISCLAIMERS: Record<DisclaimerSurface, Disclaimer> = {
  onboardingIntro: {
    id: "onboardingIntro",
    body: INTRO_BODY,
    severity: "neutral",
  },
  routineStart: {
    id: "routineStart",
    body: ROUTINE_START_BODY,
    severity: "neutral",
  },
  painPromptLow: {
    id: "painPromptLow",
    body: PAIN_LOW_BODY,
    severity: "neutral",
  },
  painPromptMedium: {
    id: "painPromptMedium",
    body: PAIN_MEDIUM_BODY,
    severity: "caution",
  },
  painPromptHigh: {
    id: "painPromptHigh",
    body: PAIN_HIGH_BODY,
    severity: "warn",
    cta: {
      label: "Find medical guidance",
      href: "/medical-guidance",
    },
  },
  safetyGate: {
    id: "safetyGate",
    body: SAFETY_GATE_BODY,
    severity: "caution",
  },
  aiGeneratedCard: {
    id: "aiGeneratedCard",
    body: AI_GENERATED_BODY,
    severity: "neutral",
  },
  marketingPainRelief: {
    id: "marketingPainRelief",
    body: MARKETING_PAIN_RELIEF_BODY,
    severity: "neutral",
  },
}

/**
 * Every known surface — iterate this in tests / audits to ensure we
 * never accidentally drop a surface out of the registry.
 */
export const DISCLAIMER_SURFACES: DisclaimerSurface[] = [
  "onboardingIntro",
  "routineStart",
  "painPromptLow",
  "painPromptMedium",
  "painPromptHigh",
  "safetyGate",
  "aiGeneratedCard",
  "marketingPainRelief",
]

/**
 * Pick the right pain-prompt disclaimer for a 0–10 pain rating.
 * Thresholds mirror `src/services/safety.ts::classifyPainRating`.
 */
export function painPromptForRating(
  rating: number,
): Disclaimer {
  if (rating >= 7) return DISCLAIMERS.painPromptHigh
  if (rating >= 4) return DISCLAIMERS.painPromptMedium
  return DISCLAIMERS.painPromptLow
}

/**
 * Convenience lookup — used by the <DisclaimerBanner/> component and by
 * audit tooling that walks the surface list at test time.
 */
export function getDisclaimer(surface: DisclaimerSurface): Disclaimer {
  return DISCLAIMERS[surface]
}
